# Generated by Django 3.2.6 on 2021-08-17 09:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('crawl', '0003_todo'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Todo',
        ),
    ]
